name: Python application CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install allure-pytest
    - name: Run tests with pytest and generate Allure results
      run: |
        pytest --clean-alluredir --alluredir allure_reports
    - name: Archive Allure results
      uses: actions/upload-artifact@v2
      with:
        name: allure-reports
        path: allure_reports
